language: node_js
node_js:
  - "8"
before_install: 
  - npm install
# blocklist
# branches:
#   except:
#   - legacy
#   - experimental

# safelist
branches:
  only:
  - dev_0.1.1
  - dev_0.1.2
  - dev_0.2
  - dev_0.3